### ISSUE TITLE
Shorthand methods aren't considered functions

### ISSUE THREAD

**Issue by olegskl** [adana-coverage/babel-plugin-transform-adana#34]
I've been playing around with adana-analyze and noticed that I get less coverage than with my previous babel5+isparta setup. Apparently, shorthand methods aren't considered functions:

``` js
{
  foo(a, b) { // this is not treated as a function
    return a + b; // this is not covered
  }
}
```

**Comment by izaakschroeder** [comment]
They are now! Should be fixed in https://github.com/adana-coverage/babel-plugin-transform-adana/pull/35 and released as part of `v0.5.5`.

Thanks again for playing around with this package – it's still the new kid on the block and it's been great to have feedback. :ok_hand: 

Other suggestions and thoughts always welcome!
